#!/usr/bin/env lua

local todofile = require('lib.todofile')

local path = './todo.md'
local tf = todofile(path)

print()
print(
	'Showing '
	.. path
	.. ' - '
	.. tf:count_todos()
	.. ' todos ('
	.. tf:count_unchecked_todos()
	.. ' open, '
	.. tf:count_checked_todos()
	.. ' closed)'
)
for k, v in pairs(tf:get_todos()) do
	print(k, v)
end
print()

tf:add_todo('Test ' .. (tf:count_todos() + 1))


--TODO: CLI
-- todolist add ./todo.md 'Do the dishes'
-- todolist check ./todo.md 'Do the dishes'
-- todolist check ./todo.md 1
-- todolist uncheck ./todo.md 'Do the dishes'
-- todolist uncheck ./todo.md 1
-- todolist list ./todo.md
-- todolist list ./todo.md --checked
-- todolist list ./todo.md --unchecked
-- todolist list ./todo.md --quiet   # only shows the list without the fancy stuff
-- todolist get ./todo.md 'Do the dishes'
-- todolist get ./todo.md 1
-- todolist update ./todo.md 'Do the dishes' 'Do the dishes tomorrow'
-- todolist update ./todo.md 1 'Do the dishes tomorrow'
-- todolist remove ./todo.md 'Do the dishes'
-- todolist remove ./todo.md 1
-- todolist remove-checked ./todo.md  # no shorthand for this one since destructive
--
-- Also provide shorthands for the commands above!
-- Also maybe allow the legacy commands for "backwards compatibility"
